### ISSUE TITLE
6591 Cable unsupported?

### ISSUE THREAD

**Issue by FallenLeave91** [hthiery/python-fritzhome#20]
Hi guys, I just got a new FB from my provider. Sadly fritzhome doesn´t seem to work with it. I´m using it through HomeAssistant. Already created an [issue ](https://github.com/home-assistant/core/issues/33362) there and was redirected here :).

Any Idea about this problem?

**Comment by hthiery** [comment]
Hi, did you an user for the smarthome access with the special access rights?

**Comment by FallenLeave91** [comment]
Yes did that.
[Imgur](https://i.imgur.com/KShd89Y.png)

**Comment by FallenLeave91** [comment]
Sorry maybe it´s not an issue at all. I installed fritzhome locally and tried the actors command:
`Wohnzimmer Heizung (AVM FRITZ!DECT 301; AIN 09995 0249073 )
Temp: act 19.5 target 19.0; battery (low): False
Temp (via get): act 19.5 target 19.0`

Maybe it´s a HomeAssistant Issue but it has been working with the same Version before.

**Comment by hthiery** [comment]
hi .. do you have any news on that?

**Comment by FallenLeave91** [comment]
Suddenly it appears to be working again. Maybe it had something to do with my network irdk. Can be closed.
