### ISSUE TITLE
Enable firmware version readout

### ISSUE THREAD

**Issue by sisamiwe** [hthiery/python-fritzhome#21]
Hey,
currently the read out of the device' firmware version is not fully implemented.
Please enable the firmware version readout.
Thank you.

**Comment by hthiery** [comment]
Hi,
would you like to prepare a pull request for that?

**Comment by sisamiwe** [comment]
Function was already available; Just made a PR adding the fw_version variable initialisiation

**Comment by hthiery** [comment]
fixed by #22
