### ISSUE TITLE
Support non-standard ports

### ISSUE THREAD

**Issue by tobox** [hthiery/python-fritzhome#25]
I had to configure my Fritz!Box to a TCP port different from 443. Can you provide a parameter to specify the port?

I am not using python-fritzhome directly, but through home assistant, where I have also opened a related issue:

https://github.com/home-assistant/core/issues/36903

**Comment by hthiery** [comment]
just take a quick look on it but as far as I can see you should set the right port just in the url.

e.g. for port 1234: host=`10.0.0.1:1234`

https://stackoverflow.com/questions/25582875/set-port-in-requests

**Comment by tobox** [comment]
The problem seems to be somewhere else... I will first check the home assistant part.

python-fritzhome seems to work fine on the command line without any specific port setting.
