### ISSUE TITLE
Please release a new version to PyPi that includes the HTTPS support

### ISSUE THREAD

**Issue by cb109** [hthiery/python-fritzhome#34]
Thank you for for creating and sharing this library, I am using it to control my thermostats 👍 

There are a number of changes since the last release in February, most noticeably HTTPS support (https://github.com/hthiery/python-fritzhome/pull/19). It would be great to be able to install the latest code from PyPi that includes the HTTPS support, maybe you can find the time to release a new version at some point. 

Will install from Github directly until then, no worries. Thanks for your time!

**Comment by hthiery** [comment]
Hi, I will release a new version soon. I'm still struggling to change the deploy to github actions.
