### ISSUE TITLE
No switches detected for Fritz!DECT 440

### ISSUE THREAD

**Issue by BenPru** [hthiery/python-fritzhome#35]
My Fritz!DECT 440 is only detectet as sensor for temperature.
The four switch buttons can not be used.

##############################
name=Taster Schlafzimmer
  ain=nnnnn nnnnnnn
  id=16
  productname=FRITZ!DECT 440
  manufacturer=AVM
  present=True
  lock=None
  devicelock=None
 Temperature:
  temperature=23.0
  offset=0.0
##############################
name=Taster Wohnzimmer
  ain=nnnnn nnnnnnn
  id=17
  productname=FRITZ!DECT 440
  manufacturer=AVM
  present=True
  lock=None
  devicelock=None
 Temperature:
  temperature=23.0
  offset=0.0

See output from http://fritz.box/webservices/homeautoswitch.lua?switchcmd=getdevicelistinfos&sid=
with button tags:
[homeautoswitch.zip](https://github.com/hthiery/python-fritzhome/files/5725073/homeautoswitch.zip)

**Comment by hthiery** [comment]
Hi,

indeed, currently the new nodes that support buttons are not implemented yet.

**Comment by BenPru** [comment]
I have created pull requests to add the button function.

**Comment by hthiery** [comment]
Hi. I've taken your patches and refactored that. See the last commit. Thank you.

**Comment by BenPru** [comment]
@hthiery Are there any plans for a new release with this feature?
I would like to use it with home assistant.

**Comment by hthiery** [comment]
Hi, I will release a new version on pypi soon. I'm struggling with using github actions to deploy to pypi.

**Comment by BenPru** [comment]
@hthiery Any news for pypi? 🙈

**Comment by hthiery** [comment]
Hi @BenPru. Unfortunately I had no time to take a closer look into that. In the past I did deploy to pypi with travis. But I would like to switch to github actions. Currently I have a problem with the deploy action to detect if a commit is tagged. Maybe you have some experience on that or you're interested in figuring out what is wrong here?
