### ISSUE TITLE
Login does not work

### ISSUE THREAD

**Issue by snipem** [hthiery/python-fritzhome#4]
I've created a user like this:

![bildschirmfoto 2017-11-20 um 20 17 38](https://user-images.githubusercontent.com/985581/33036834-eba77574-ce2f-11e7-97a2-70e5b36f0ef8.png)

It'll end up with the following error:

```
[matze@server ~]$ fritzhome -u smarthome -p ****** -f 192.168.178.1 list
WARNING:pyfritzhome.fritzhome:login failed 0000000000000000
Traceback (most recent call last):
  File "/usr/bin/fritzhome", line 11, in <module>
    load_entry_point('pyfritzhome==0.3.5', 'console_scripts', 'fritzhome')()
  File "/usr/lib/python2.7/site-packages/pyfritzhome/cli.py", line 162, in main
    fritzbox.login()
  File "/usr/lib/python2.7/site-packages/pyfritzhome/fritzhome.py", line 103, in login
    raise LoginError(self._user)
pyfritzhome.errors.LoginError: login for user="smarthome" failed
```
Password was replaced.

Tried with both Python2 and 3. What could be the problem?

**Comment by hthiery** [comment]
what version of fritzbox do you have? did you tried to login to the fritzbox with this user/password combination?

**Comment by snipem** [comment]
The version is 06.92. I can't login with that user. Only with my root account. Is there any option to login with username + password?

**Comment by hthiery** [comment]
is the user smarthome the only user you have or is this an additional user?

**Comment by snipem** [comment]
I figured it out, I had no other users allowed to access the fritzbox user interface directly besides my no name "root" user.

I had to switch this setting from the second radio button to the first one:

![bildschirmfoto 2017-11-26 um 22 08 20](https://user-images.githubusercontent.com/985581/33244381-5a6c2976-d2f6-11e7-926c-d1d537c1c346.png)

Now everything is working. Thank you!
