### ISSUE TITLE
Bump Home Assistant dependency of python-fritzhome to version 0.6.0 to allow the support for FRITZ DECT 440 and 550

### ISSUE THREAD

**Issue by altso2222** [hthiery/python-fritzhome#47]
To allow the support for the FRITZ DECT 440 switch and the FRITZ DECT 500 light bulb, the HA dependency to python-fritzhome has to be bumped to version 0.6.0.

Link to current version of python-fritzhome: https://github.com/hthiery/python-fritzhome/tree/0.6.0

Inititial discussion: https://community.home-assistant.io/t/support-for-avm-fritz-dect-switch-440-and-light-bulb-500/224433/13

**Comment by mib1185** [comment]
first 0.6.0 needs to be released and published on pypi - it is still on 0.4.2 -> https://pypi.org/project/pyfritzhome

**Comment by hthiery** [comment]
Hi. Just released version 0.6.1 on pypi. The reason it was not done before was a lack of time and some issue when switching to github actions. I hope you can go on with your work on homeassistant. Let me know if there are some issues.

**Comment by mib1185** [comment]
Hi @hthiery 
many thanks for the release 🙂 
First I will test and bump to 0.6.1 on HA ... afterwards will start implementing support for 440 and 500.

**Comment by mib1185** [comment]
Hi @altso2222 , please re-open this issue, since the work is not done yet ;)

**Comment by flabbamann** [comment]
Hi @hthiery would you please release a new version containing the color temperature improvements by @mib1185 so this can be used in Home Assistant? Thank you 🙂

**Comment by hthiery** [comment]
@flabbamann done!
