### ISSUE TITLE
Integrate "T SmartHome Wandtaster"

### ISSUE THREAD

**Issue by devUBi** [hthiery/python-fritzhome#82]
I have the above mentioned new [button](https://www.smarthome.de/geraete/smarthome-wandtaster-weiss) device. It's detected in home assistant but does not show up as device.
Is it possible to integrate it?

These are the debug infos:

```xml
<device identifier="11934 0142125" id="408" functionbitmask="1" fwversion="31.20"
    manufacturer="0x0feb" productname="HAN-FUN">
    <present>1</present>
    <txbusy>0</txbusy>
    <name>HAN-FUN #3</name>
</device>
<device identifier="11934 0142125-2" id="2004" functionbitmask="8200" fwversion="0.0"
    manufacturer="0x0feb" productname="HAN-FUN">
    <present>1</present>
    <txbusy>0</txbusy>
    <name>HAN-FUN #3 - F2</name>
    <etsiunitinfo>
        <etsideviceid>408</etsideviceid>
        <unittype>273</unittype>
        <interfaces>772</interfaces>
    </etsiunitinfo>
    <button>
        <lastpressedtimestamp>1675603423</lastpressedtimestamp>
    </button>
</device>
<device identifier="11934 0142125-1" id="2005" functionbitmask="8200" fwversion="0.0"
    manufacturer="0x0feb" productname="HAN-FUN">
    <present>1</present>
    <txbusy>0</txbusy>
    <name>HAN-FUN #3 - F1</name>
    <etsiunitinfo>
        <etsideviceid>408</etsideviceid>
        <unittype>273</unittype>
        <interfaces>772</interfaces>
    </etsiunitinfo>
    <button>
        <lastpressedtimestamp>1675603422</lastpressedtimestamp>
    </button>
</device>

**Comment by devUBi** [comment]
Maybe i should add my usecase for that button.
If one of that button's is pressed an automation inside home assistant should be triggered to switch on a light (for example conneted to a shelly device).
So having the `last_pressed` attribute exposed to the HA button entity and updated by the polling, would be perfect (at least for me)

**Comment by MattBavaria** [comment]
Hello,

this issue basically has been discussed here:
[HomeAssistant support for AVM switch 440](https://community.home-assistant.io/t/support-for-avm-fritz-dect-switch-440-and-light-bulb-500/224433)
The fact, that you would have to poll the state, would lead to delay and no good usability.
As AVM introduced webhookfeature with 7.5x, maybe that would help you out.
Usage is described in nhe linked thread as well.

Regards,
MattBavaria

**Comment by mib1185** [comment]
going to close this, since all has been discussed in the by @MattBavaria  mentioned thread
