### ISSUE TITLE
New feature request - set holiday dates

### ISSUE THREAD

**Issue by monojk** [hthiery/python-fritzhome#98]
I have a dozen thermostats at home that I want to set the holidays by one command (in the fritz user interface I would have to set the same holiday a dozen times i.e. for each thermostat).
Thought I could do that with a fritzhome template but with `fritzhome -f fritz.box -u xxx -p yyy template list` I get nothing (though holidays exist).

**Comment by mib1185** [comment]
did you already create the template you want to apply via `fritzhome` command?

**Comment by monojk** [comment]
Ah, I understand now. Closing
